trust_level_flair_position:
  default: "bottom-left"
  type: enum
  choices:
    - "bottom-right"
    - "top-right"
    - "top-left"
    - "overlap"
group_flair_always_on_top:
  default: true
  type: bool
  description: "For positions where the trust flair overlaps, or is in the same position as group flair."
use_font_awesome:
  default: false
  type: bool
  description: "<span>Use font awesome in the flair icon fields below. Accepted 
    formats: \"fa-icon\", \"far fa-icon\" or \"fab fa-icon\". 
    <a href='https://fontawesome.com/icons?d=gallery&m=free' target='_blank'>Click Here</a> 
    to view the list of availible icons."
font_awsome_color:
  default: "#ffffff"
  type: string
font_awsome_background_color:
  default: "#000000"
  type: string
new_user_flair_icon:
  default: ""
  type: string
  description: "The image URL for the new user trust level (TL0).
    TIP: Upload your images to a local theme component. Once uploaded, right-click on the upload link,
    copy the image address, then paste the link into this textbox."
basic_user_flair_icon:
  default: ""
  type: string
  description: "The image URL for the basic user trust level (TL1)."
member_flair_icon:
  default: ""
  type: string
  description: "The image URL for the member trust level (TL2)."
regular_flair_icon:
  default: ""
  type: string
  description: "The image URL for the regular trust level (TL3)."
leader_flair_icon:
  default: ""
  type: string
  description: "The image URL for the leader trust level (TL4)."
exclude_nonhuman_users:
  default: true
  type: bool
  description: "Flair will not be displayed on the system and discobot users"
